### ISSUE TITLE
sql needs update for so payments

### ISSUE THREAD

**Issue by proseLA** [proseLA/authorizenet_cim#1]
if someone has already installed so and so payments the sql should be modified to alter the table as opposed to dumping it

**Comment by proseLA** [comment]
> > when i go here:
> > https://www.zen-cart.com/downloads.php?do=file&id=155&styleid=2
> 
> Aside: do you regularly browse the forum using the vBulletin default template instead of the Zen Cart template? ie: `&styleid=2`



> > _ALERT THREAD HIJACK!!_
> > yes, i do. why?
> 
> Just curious: why? :)

@drbyte are you aware that the 2 templates do not have the same functionality?  at all.

**Comment by drbyte** [comment]
I guess I'm not.
I know we've never maintained the default template, so I'm sure it's missing tons of things that are in the branded template.

What functionality are you referring to? and desktop or mobile?

**Comment by proseLA** [comment]
always desktop.  i never use the mobile part of it.

the issues discussed here:

https://www.zen-cart.com/showthread.php?226692-plugins-missing-image-and-php-5-3-safe&p=1368697#post1368697

and here:

https://www.zen-cart.com/showthread.php?226704-Github-button-does-not-appear&p=1368694#post1368694

**Comment by drbyte** [comment]
Update: Yes I'm aware that lots of things customized in the Zen Cart skin are NOT in the default vB skin. There are no plans to waste time backporting things.

What's the reason for NOT using the Zen Cart skin?

**Comment by proseLA** [comment]
as i stated on 3/23, i was playing around and liked it more.  i suppose i find the orange buttons a bit offensive on my eyes.

when we were discussing it then, i suppose i would have appreciated a heads up that using that template loses some functionality, as opposed to the just curious response.  perhaps it slipped your mind, i do not know...  i just find it curious that you brought it up then. 
 
my question (for which i do not need an answer) is why make a skin available if it loses functionality?  perhaps one can not remove that default skin on the forum, i do not know.  i have never configured a vBulletin forum before.  some of the wikis that i have configured do offer multiple skins, but losing functionality has NEVER been an issue on those wikis....  as far as i can tell.

water under the bridge as far as i am concerned.

**Comment by drbyte** [comment]
I apologize for not adding that clarification. I remember thinking it and intending to mention it, but if I failed to do it, I'm sorry. 
One of the reasons for keeping the old skin enabled is because I can't delete it because it's also the "master" (kinda like template_default), and if someone "does" switch to it if there's no nav menu to switch back with then they get caught in some sort of no-man's land. A bit of an annoying trait with vB.
