### ISSUE TITLE
explore jeking issue with FEC

### ISSUE THREAD

**Issue by proseLA** [proseLA/authorizenet_cim#24]
not sure if true....  guest checkout storing credit card

**Comment by lat9** [comment]
I don't know either, but you should disallow the credit-card's storage/re-use if `zen_in_guest_checkout()` returns `(bool)true`.

**Comment by proseLA** [comment]
unfortunately, he has sent me on wild goose chases before.  he may be right on this one.  i'm still testing.

i am also not a fan of the ```zen_x``` functions that really should be in a class file, ie a customer class...  going to be hard to get around that.  but i still can dream....
