### ISSUE TITLE
recommended change for 1.5.8

### ISSUE THREAD

**Issue by scottcwilson** [proseLA/authorizenet_cim#55]
But backwards compatible: 
includes/modules/payment/authorizenet_cim.php
In cimUpdatedByAdminName() check if (IS_ADMIN_FLAG === true) because you only want to return zen_updated_by_admin() if you are called in admin context.
The function zen_updated_by_admin() moved into the storefront fileset in this PR:
https://github.com/zencart/zencart/pull/4627

No harm in this change in older releases; still works the same way.

**Comment by proseLA** [comment]
thanks, i'll take a look.

**Comment by proseLA** [comment]
i'm a fan of boolean flags without comparing to a boolean value.  thanks for pointing out this change.
